var IS_DEVELOPER = false;
var IS_MUTE = false;
var PUBLISH_KEY = "pub-c-aedde538-6a7a-4e15-98e9-3785df1d355c";
var SUBSCRIBE_KEY = "sub-c-13b753b4-cc4e-11e3-9782-02ee2ddab7fe";
var TRANGTHAI_DATXE_ARRAY = [1, 2, 3, 11, 12];
//1: Đang gọi xe, 2: Khách hàng hủy từ đầu, 3: Khách hàng tìm không được lái xe, 11:Khách hàng hủy trên đường lái xe đến đón khách, 12: Lái xe hủy trên đường đón khách hàngvar PASTAXI_DRIVER = "PASTAXI_DRIVER";  //Lấy vị trí, trạng thái bận rỗi của lái xe
var PASGO_ALERT_SHOWNOTE = "PASGO_ALERT_SHOWNOTE"; // Dung de notify cac thao tac cua tong dai vien cho tong dai vien khac cung biet 
var PASTAXI_LOCATION_SERVER = "PASTAXI_LOCATION_SERVER";  //Lấy vị trí của cac tai xe theo TinhId
var PASTAXI_ORDER_STATUS = "PASTAXI_ORDER_STATUS";//Lấy trạng thái của giao dịch(đang làm)
var PASTAXI_CLIENT = "PASTAXI_DEVELOPER_CLIENT";
var PASTAXI_ONEPAS_HANGXE_PUBNUB = "PASTAXI_ONEPAS_HANGXE_PUBNUB";
var PASTAXI_PARNER_ONEPAS_CHECKIN_PUBNUB = "PASTAXI_PARNER_ONEPAS_CHECKIN";